# Generated by Django 4.1.7 on 2023-03-10 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='message',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.secretmessage'),
        ),
    ]
